// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

@TestInstance(Lifecycle.PER_CLASS)
public class Test4 {
  private WebDriver driver;

  @BeforeAll
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
	driver = new ChromeDriver();
    
  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test4() {
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(972, 978));
    driver.findElement(By.cssSelector(".clearbtn")).click();
    driver.findElement(By.name("vx")).click();
    driver.findElement(By.name("vx")).sendKeys("a");
    driver.findElement(By.name("vy")).click();
    driver.findElement(By.name("vy")).sendKeys("b");
    driver.findElement(By.name("vz")).click();
    driver.findElement(By.name("vz")).sendKeys("c");
    driver.findElement(By.xpath("//input[@value=\'Calculate\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//font[contains(.,\'Please provide 3 positive values, including at least one side.\')]")));
    }
  }
}
