// Generated by Selenium IDE
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

@TestInstance(Lifecycle.PER_CLASS)
public class Test2 {
  private WebDriver driver;
  
  @BeforeAll
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");
    driver = new ChromeDriver();

  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
	  
    driver.get("https://www.calculator.net/triangle-calculator.html");
    driver.manage().window().setSize(new Dimension(972, 978));
    driver.findElement(By.name("angleunits")).click();
    {
      WebElement dropdown = driver.findElement(By.name("angleunits"));
      dropdown.findElement(By.xpath("//option[. = 'radian']")).click();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[@id=\'dg3\'][.=\'r\']")));
    }
    driver.findElement(By.name("angleunits")).click();
    {
      WebElement dropdown = driver.findElement(By.name("angleunits"));
      dropdown.findElement(By.xpath("//option[. = 'degree °']")).click();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//span[@id=\'dg3\'][.=\'°\']")));
    }
    
  }
}
